package com.mycompany.views;


import com.mycompany.ilib.DAOpolizasImpl;
import static com.mycompany.ilib.Dashboard.ShowJPanel;
import com.mycompany.interfaces.DAOpolizas;
import com.mycompany.models.polizas;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class PolizasSeguro extends javax.swing.JPanel {

    boolean isEdition = false;
    polizas polizasEdition;

    public PolizasSeguro() {
        initComponents();
        InitStyles();
    }
 public PolizasSeguro(com.mycompany.models.polizas Polizas){
        initComponents();
        isEdition =true;
        polizasEdition=Polizas;
        InitStyles();
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setForeground(Color.black);
        txtncontrato.putClientProperty("JTextField.placeholderText", "Ingrese el Número de Contrato");
        txtnombre.putClientProperty("JTextField.placeholderText", "Ingrese Nombres.");
        txtapellido.putClientProperty("JTextField.placeholderText", "Ingrese Apellidos.");
        txtcedula.putClientProperty("JTextField.placeholderText", "Ingrese la Cédula.");
        txtfechan.putClientProperty("JTextField.placeholderText", "Ingrese la Fecha Nacimiento.");
        txttelefono.putClientProperty("JTextField.placeholderText", "Ingrese el Teléfono.");
        txtdireccion.putClientProperty("JTextField.placeholderText", "Ingrese Direccion.");
        txtcorreo.putClientProperty("JTextField.placeholderText", "Ingrese Correo.");
        txtprofesion.putClientProperty("JTextField.placeholderText", "Ingrese Profesión");
        txtconvenio.putClientProperty("JTextField.placeholderText", "Ingrese Convenio.");
        txtplan.putClientProperty("JTextField.placeholderText", "Ingrese Tipo de plan.");

        if(isEdition){
        button.setText("Actualizar");
        
        if(polizasEdition != null){
       
         txtncontrato.setText(polizasEdition.getnumerocontrato());
         txtnombre.setText(polizasEdition.getnombre());
           txtapellido.setText(polizasEdition.getapellido());
            txtcedula.setText(polizasEdition.getcedula());
               txtfechan.setText(polizasEdition.getfecha_nacimiento());
                 txttelefono.setText(polizasEdition.gettelefono());
                   txtdireccion.setText(polizasEdition.getdireccion());
                      txtcorreo.setText(polizasEdition.getcorreo());
                       txtprofesion.setText(polizasEdition.getprofesion());
                          txtconvenio.setText(polizasEdition.getconevnio());
                   txtplan.setText(polizasEdition.getplan());
                          
           
       
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        txtncontrato = new javax.swing.JTextField();
        dateLbl = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        authorLbl = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        catLbl = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        edLbl = new javax.swing.JLabel();
        txtfechan = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        langLbl = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        pagsLbl = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        descLbl = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        stockLbl = new javax.swing.JLabel();
        txtprofesion = new javax.swing.JTextField();
        txtconvenio = new javax.swing.JTextField();
        dispLbl = new javax.swing.JLabel();
        ejemLbl = new javax.swing.JLabel();
        txtplan = new javax.swing.JTextField();
        button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("Polizas de Seguro");

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(51, 51, 51));
        titleLbl.setText("Nùmero de contrato Prevención Familiar");

        dateLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(51, 51, 51));
        dateLbl.setText("Nombre del contratante");

        authorLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        authorLbl.setForeground(new java.awt.Color(51, 51, 51));
        authorLbl.setText("Apellidos del Contratante");

        catLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        catLbl.setForeground(new java.awt.Color(51, 51, 51));
        catLbl.setText("DNI/Cèdula del Contratante");

        edLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edLbl.setForeground(new java.awt.Color(51, 51, 51));
        edLbl.setText("Fecha de Nacimiento del contratrante");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        langLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        langLbl.setForeground(new java.awt.Color(51, 51, 51));
        langLbl.setText("Telèfono");

        txttelefono.setToolTipText("");

        pagsLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pagsLbl.setForeground(new java.awt.Color(51, 51, 51));
        pagsLbl.setText("Direccion Del contratante");

        txtdireccion.setToolTipText("");

        descLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        descLbl.setForeground(new java.awt.Color(51, 51, 51));
        descLbl.setText("Correo");

        txtcorreo.setToolTipText("");

        stockLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stockLbl.setForeground(new java.awt.Color(51, 51, 51));
        stockLbl.setText("Profesión");
        stockLbl.setToolTipText("");

        txtprofesion.setToolTipText("");

        txtconvenio.setToolTipText("");

        dispLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dispLbl.setForeground(new java.awt.Color(51, 51, 51));
        dispLbl.setText("Convenio");

        ejemLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejemLbl.setForeground(new java.awt.Color(51, 51, 51));
        ejemLbl.setText("Tipo de Plan");

        txtplan.setToolTipText("");

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Subir");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(553, 553, 553))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcedula)
                            .addComponent(txtapellido)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(authorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(233, 233, 233))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(catLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(213, 213, 213))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(234, 234, 234))
                            .addComponent(txtncontrato)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(dateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(161, 161, 161))
                            .addComponent(txtnombre)
                            .addComponent(txtfechan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(edLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(227, 227, 227)))
                        .addGap(68, 68, 68)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttelefono)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(langLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(228, 228, 228))
                            .addComponent(txtdireccion)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(pagsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(223, 223, 223))
                            .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(descLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(206, 206, 206))
                            .addComponent(txtcorreo)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtprofesion)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(stockLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(94, 94, 94)))
                                .addGap(20, 20, 20)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(dispLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(67, 67, 67))
                                    .addComponent(txtconvenio)))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(ejemLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(208, 208, 208))
                            .addComponent(txtplan))
                        .addGap(72, 72, 72))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(langLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stockLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dispLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprofesion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtconvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(ejemLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtplan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtncontrato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(catLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfechan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
public boolean isEmail (String correo){
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(correo);
        if(mat.find()){
            return true;
        }else{
            return false;
        }
    }
    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
      String numerocontrato=txtncontrato.getText();
      String nombre=txtnombre.getText();
      String apellido=txtapellido.getText();
       String cedula=txtcedula.getText();
      String fecha_nacimiento=txtfechan.getText();
      String telefono=txttelefono.getText();
      String direccion=txtdireccion.getText();
      String correo=txtcorreo.getText();
       String profesion=txtprofesion.getText();
        String convenio=txtconvenio.getText();
         String plan=txtplan.getText();
      
         
            if(cedula.isEmpty()){
 javax.swing.JOptionPane.showMessageDialog(this, "Debe colocar al menos una cedula. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
         
            return;}

         
      if(!isEmail(txtcorreo.getText())){
            JOptionPane.showMessageDialog(null, "¡Debes validar el email!", "ATENCIÓN ADMINISTRADOR", JOptionPane.WARNING_MESSAGE);
           txtcorreo.requestFocus();
           return;
}
      
    
        
        
com.mycompany.models.polizas Polizas=isEdition ? polizasEdition : new com.mycompany.models.polizas();

Polizas.setnumerocontrato(numerocontrato);
Polizas.setnombre(nombre);
Polizas.setapellido(apellido);
Polizas.setcedula(cedula);
Polizas.setfecha_nacimiento(fecha_nacimiento);
Polizas.settelefono(telefono);
Polizas.setdireccion(direccion);
Polizas.setcorreo(correo);
Polizas.setprofesion(profesion);
Polizas.setconvenio(convenio);
Polizas.setplan(plan);

   try{
   DAOpolizas dao= new DAOpolizasImpl();
   
   
   if(!isEdition)
      dao.registrar(Polizas);
 
   else 
       
           dao.modificar(Polizas);
  
   String succesMessage = isEdition ? "Modificado" : "Registrado";
        javax.swing.JOptionPane.showMessageDialog(this, "Usuario "+succesMessage+ " exitosamente. \n", "AVISO",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        if(!isEdition){ 
            txtncontrato.setText("");
           txtnombre.setText("");
            txtapellido.setText("");
         txtfechan.setText("");
            txttelefono.setText("");
            txtdireccion.setText("");
            txtcorreo.setText("");
            txtprofesion.setText("");
            txtconvenio.setText("");
            txtplan.setText("");
            txtcedula.setText("");
            
        }
            
   }   catch (Exception e){
 String errorMessage = isEdition ? "Modificar" : "Registrar";
        javax.swing.JOptionPane.showMessageDialog(this, "Ocurrio un error al "+errorMessage+ " el usuario. \n", "AVISO",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        System.out.println(e);
   }  

        
        

           
    }//GEN-LAST:event_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLbl;
    private javax.swing.JPanel bg;
    private javax.swing.JButton button;
    private javax.swing.JLabel catLbl;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel descLbl;
    private javax.swing.JLabel dispLbl;
    private javax.swing.JLabel edLbl;
    private javax.swing.JLabel ejemLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel langLbl;
    private javax.swing.JLabel pagsLbl;
    private javax.swing.JLabel stockLbl;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtconvenio;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtfechan;
    private javax.swing.JTextField txtncontrato;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtplan;
    private javax.swing.JTextField txtprofesion;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}